// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzMf04XH2lEH2p_xkDgBOInWEx5xTT768',
    appId: '1:325351443413:web:1f34b3d8db31f1ca3f8b5c',
    messagingSenderId: '325351443413',
    projectId: 'tradehub-4b955',
    authDomain: 'tradehub-4b955.firebaseapp.com',
    storageBucket: 'tradehub-4b955.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfnLLDLzLCSUKMsGPWUkqQ42Mv_HUyV4o',
    appId: '1:325351443413:android:9b05a365f06c8b863f8b5c',
    messagingSenderId: '325351443413',
    projectId: 'tradehub-4b955',
    storageBucket: 'tradehub-4b955.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJyU7dJA3_EWZhp-qTSqn51Vgpewpq4tw',
    appId: '1:325351443413:ios:4fd431e7b39a979f3f8b5c',
    messagingSenderId: '325351443413',
    projectId: 'tradehub-4b955',
    storageBucket: 'tradehub-4b955.appspot.com',
    iosBundleId: 'com.example.tradehub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJyU7dJA3_EWZhp-qTSqn51Vgpewpq4tw',
    appId: '1:325351443413:ios:3d9d302fc7e84b3b3f8b5c',
    messagingSenderId: '325351443413',
    projectId: 'tradehub-4b955',
    storageBucket: 'tradehub-4b955.appspot.com',
    iosBundleId: 'com.example.tradehub.RunnerTests',
  );
}
